[package]
name = "CHANGE_ME"
version = "CHANGE_ME"
edition = "2021"

[features]
default = ["prost-serde"]
prost-serde = [
    "dep:serde",
    "dep:prost",
    "dep:prost-types",
    "dep:prost-wkt",
    "dep:prost-wkt-types",
    "dep:tonic",
]

[dependencies]
prost = { version = "0.13.5", optional = true }
prost-types = { version = "0.13.5", optional = true }
prost-wkt = { version = "0.6.0", optional = true }
prost-wkt-types = { version = "0.6.0", optional = true }
serde = { version = "1.0.218", optional = true, features = ["derive", "std"] }
tonic = { version = "0.12.3", optional = true }

[build-dependencies]
anyhow = { version = "1.0.95" }
appbiotic-api-prost-serde-build = { version = "0.1.0", path = "../../../api-build/crates/prost-serde-build" }
appbiotic-api-protogen-spec = { version = "0.1.0", path = "../../../api-build/crates/protogen-spec" }
prost-build = { version = "0.13.5" }
prost-wkt-build = { version = "0.6.0" }
serde_json = { version = "1.0.139", features = ["std"] }
tonic-build = { version = "0.12.3" }
